### ISSUE TITLE
Should add design document for node affinity

### ISSUE THREAD

**Issue by m1093782566** [kubernetes-sigs/poseidon#106]
As we almost finished the review work on node selector and node affinity design for firmament/poseidon scheduler, should we add the markdown-type document to this project? e.g. create a `docs/design` folder and drop the document in.

BTW, contributors should send design document PR before starting feature developing.

**Comment by deepak-vij** [comment]
Definitely, we need to convert the GoogleDoc to MD format.

Also, going forward we need to have the design document ready prior to doing implementation. Till now, we have been following code-first approach. Going forward, as we are much more comfortable with the codebase and overall design, we need to follow the design document first approach. As a matter of fact, this is what we are doing for Pod Affinity as well as Taints and Tolerations work as well.

**Comment by deepak-vij** [comment]
Design document is already created now. Closing this issue.
https://github.com/kubernetes-sigs/poseidon/blob/master/docs/design/node_affinity_and_selector_for_poseidon.md
