### ISSUE TITLE
should record events during pod/node was watched, pod scheduled/deleted and failed tasks

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes-sigs/poseidon#110]
as title described, events should be recorded to let the users know what happens during one scheduling task:
1, event for one pod watched, task submitted to firmament, failed/successful tasks from firmament and the reasons 
2, event for on node watched/deleted

**Comment by jiaxuanzhou** [comment]
event for pod supported by #138

**Comment by shivramsrivastava** [comment]
This issue is addressed by the PR #138.
We now have events support in Poseidon, success and failure events are sent from Poseidon after this PR.
Hence closing this issue.
