### ISSUE TITLE
poseidon should cache the node of the cluster

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes-sigs/poseidon#115]
1, cache the node obj to generate the resource view of the nodes in the cluster
2, optional but useful :  capability to provide api to get the whole resource usage of the cluster

**Comment by deepak-vij** [comment]
@jiaxuanzhou you want to work on this issue. Otherwise, we can close this for the time being. We can always re-open it once we have someone available to implement this. Thanks.

**Comment by deepak-vij** [comment]
Closing this for now. We will re-open it at a later time.
