### ISSUE TITLE
The scheduling_ prefix to the repo name is no longer required

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes-sigs/poseidon#13]
Feel free to rename the repo.

**Comment by deepak-vij** [comment]
This is great. Thanks Brian.
@timothysc, should we go ahead and rename it ourselves or you need to do that? Thanks.

cc: @shivramsrivastava @timothysc @ICGog @ms705 @dhilipkumars

**Comment by dhilipkumars** [comment]
It is done now. Please close this issue.
