### ISSUE TITLE
Maybe we need more documentation and architectural design instructions for scheduling_poseidon

### ISSUE THREAD

**Issue by wgliang** [kubernetes-sigs/poseidon#14]

**Comment by deepak-vij** [comment]
Please be patient. We are still in the process of setting up the environment. We will publish all related details as soon as possible. Thanks.

**Comment by wgliang** [comment]
Looking forward to it.

**Comment by Violet-Guo** [comment]
Looking forward to it.

**Comment by lioncruise** [comment]
Looking forward to it.

**Comment by dhilipkumars** [comment]
Hi all, could you all please check the latest documentation update. If the documentation is sufficient we can close this.

**Comment by deepak-vij** [comment]
We have added reasonably good documentation now. I am closing this issue for now. Thanks.

**Comment by wgliang** [comment]
Ok, Thanks great work.
