### ISSUE TITLE
`make` fails after running `dep ensure` and `hack/update-bazel.sh`

### ISSUE THREAD

**Issue by islinwb** [kubernetes-sigs/poseidon#144]
**What happened**:
`make` fails after running `dep ensure` and `hack/update-bazel.sh`

**How to reproduce it (as minimally and precisely as possible)**:
1. fetch the code in `master`
2. run `dep ensure` and `hack/update-bazel.sh`
3. run `make`

the error occurs:
```
can't load package: package github.com/kubernetes-sigs/poseidon/vendor/k8s.io/kubernetes/hack/cmd/teststale: cannot find package "github.com/kubernetes-sigs/poseidon/vendor/k8s.io/kubernetes/hack/cmd/teststale" in any of:  
.....
```
**Possible cause**
In v1.11.0(https://github.com/kubernetes-sigs/poseidon/blob/master/Gopkg.toml#L52-L54), `teststale` has been removed (https://github.com/kubernetes/kubernetes/pull/62151/commits/46146f6f3dadc84301b86ce8492adfa06171d6c3)

https://github.com/kubernetes-sigs/poseidon/pull/143 cherry-picks part of https://github.com/kubernetes/kubernetes/pull/62151/commits/46146f6f3dadc84301b86ce8492adfa06171d6c3.  That means we need to update the `go` version to v1.10.*?

**Comment by m1093782566** [comment]
I have no attachment of go version as long as it works fine with poseidon project.
