### ISSUE TITLE
Redundant License files present in sub-directories

### ISSUE THREAD

**Issue by asifdxtreme** [kubernetes-sigs/poseidon#158]
There are some redundant license files which are present in some sub-directories, it is generally recommended to put all these files in a licenses folder and refer this license file wherever used or just put a usage notice for these files in main License file.
 - [ ] All txt files in https://github.com/kubernetes-sigs/poseidon/tree/master/hack/boilerplate

**Comment by deepak-vij** [comment]
Leaving this open at this time, we will get to it soon.
