### ISSUE TITLE
Maintainer rights

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes-sigs/poseidon#16]
Hi @timothysc @bgrant0607 @spiffxp 

As maintainers of this project, we need the ability 
1. close issues / PRs 
2. update issues and PR titles
3. Add remove labels on the issues.

We do not have such rights as an external collaborator.  What is the best way to go about it?

maintainers: @shivramsrivastava @ICGog @irfanurrehman @shashidharatd @dhilipkumars

**Comment by bgrant0607** [comment]
@dhilipkumars Have you tried the bot commands?

/joke

https://prow.k8s.io/command-help.html

**Comment by bgrant0607** [comment]
I don't see a problem with adding people to the org, but we're trying to minimize the number of people with direct write access to repos.

@spiffxp Do you have a guideline for who needs access?

**Comment by timothysc** [comment]
+1 to bot commands. 

I also updated you to write access.  FWIW is gave the rights that @deepak-vij had requested.

**Comment by dhilipkumars** [comment]
Thanks @bgrant0607 and @timothysc 
Now im able to close and edit issues PRs topic and will also be able to close them.

/close
