### ISSUE TITLE
Can multiple policies be implemented simultaneously

### ISSUE THREAD

**Issue by Jianzs** [kubernetes-sigs/poseidon#179]
I read the paper, Firmament. But I met a question. Can multiple policies be implemented simultaneously? If so, when we use more than 1 policies, task nodes would connect more than one machines or aggregators. So when we extract the task placements, task nodes may receive different placements from different successor nodes. How to handle this?

**Comment by deepak-vij** [comment]
I don't think you can apply multiple scheduling policies simultaneously at a given time. You would need to implement/incorporate multiple policies as one consolidated policy, if this is what you desire. Thanks.

**Comment by Jianzs** [comment]
Good idea! Thanks! If I want to put data locality policy and network-aware policy together, I can make them as one consolidated policy. Probably, there are two arcs between one task and one machine, because of two sub policies. But take node have only one unit flow. Finally, the flow will proceed through one of arcs mentioned above. So, when we extract the task placements, each task node is paired only one machine.  Right?

**Comment by deepak-vij** [comment]
Correct. One consolidated policy that factors in locality & network awareness together while assigning cost to an arc should work.

**Comment by Jianzs** [comment]
OK. Thank you!
