### ISSUE TITLE
how to get poseidon's metrics data

### ISSUE THREAD

**Issue by chauncey-77** [kubernetes-sigs/poseidon#181]
I want to see the scheduling time of Pods scheduled by poseidon, but i don't know to get it, that is I want  to get poseidon's metrics data. Please let me know or tell me how to do, thank you!

**Comment by deepak-vij** [comment]
Please see the link below for benchmark numbers. Thanks.

https://github.com/kubernetes-sigs/poseidon/blob/master/docs/benchmark/README.md

**Comment by chauncey-77** [comment]
> Please see the link below for benchmark numbers. Thanks.
> 
> https://github.com/kubernetes-sigs/poseidon/blob/master/docs/benchmark/README.md

Thank you for your reply, but i have seen the link already. I want to get the merics data from different situation by myself, so I can understand the advantage deeply. Please tell me more, thanks.

**Comment by deepak-vij** [comment]
Please use the detail installation steps (as per the main Poseidon landing read.me page) to install Poseidon/Firmament and try out various scenarios. Thanks.

**Comment by chauncey-77** [comment]
> Please use the detail installation steps (as per the main Poseidon landing read.me page) to install Poseidon/Firmament and try out various scenarios. Thanks.

Thanks for your reply. I have installed Poseidon/Firmament in my k8s cluster, and it works will. And then, I want to collect the metrics, but I don't how to do. Maybe there is a method to get the metrics like kube-scheduler do(using curl command), but I don't know the url. Can you tell me how to do? Thanks a lot.

**Comment by deepak-vij** [comment]
The detail benchmark testing we did, as shown in the benchmark page, was using KubeMark. It is quite tricky though. This is primarily because KubeMark does not scale beyond certain no. of hollow nodes in a cluster. This is due to API Server related memory requirements. In order to test higher no. of nodes (1000, 2000, and beyond) we had to write our own scripts as KubeMark did not work for us beyond certain no. of nodes in a cluster.

Unfortunately, we have not been able to get around to documenting the detail performance testing process at this time. Thanks.

**Comment by chauncey-77** [comment]
> The detail benchmark testing we did, as shown in the benchmark page, was using KubeMark. It is quite tricky though. This is primarily because KubeMark does not scale beyond certain no. of hollow nodes in a cluster. This is due to API Server related memory requirements. In order to test higher no. of nodes (1000, 2000, and beyond) we had to write our own scripts as KubeMark did not work for us beyond certain no. of nodes in a cluster.
> 
> Unfortunately, we have not been able to get around to documenting the detail performance testing process at this time. Thanks.

That is to say, I can't get the time consumption of each pod(or some pods) scheduling now? Or to say, I can get the scheduling time, but the number of pods should be less than a certain scale?

**Comment by chauncey-77** [comment]
The poseidon metrics can be getten using curl tool, the url is ${poseidon pod ip}:8989/metrics. Note that 8989 is the default ip defined in config.go.
