### ISSUE TITLE
How to deploy firmament flow scheduler in cluster?

### ISSUE THREAD

**Issue by chauncey-77** [kubernetes-sigs/poseidon#185]
Is there any doc about how to deploy firmament flow scheduler in cluster, like some explanation or a yaml file like this [here](https://raw.githubusercontent.com/kubernetes-sigs/poseidon/master/deploy/firmament-deployment.yaml), which I think is order to deploy firmament simple scheduler in cluster?
Thanks.

**Comment by deepak-vij** [comment]
https://github.com/camsas/firmament/blob/master/README.md#building-instructions. This is all documented under Developer guide document link as below.

https://github.com/kubernetes-sigs/poseidon/blob/master/docs/devel/README.md
