### ISSUE TITLE
A question about how many pods can be scheduled at one time using poseidon.

### ISSUE THREAD

**Issue by chauncey-77** [kubernetes-sigs/poseidon#186]
Hi, this is my situation:
I try to schedule 300 pods at one time, but it likes that poseidon will divide the 300 pods into two part, e.g. 185 pods and 115 pods, and schedule each part alone. I want to know what factors lead to such division, and the possibility of increasing the number of pods scheduled at one time, so I read the code for a long time but have no conclusion. Please give me some tips and help, thanks.

**Comment by deepak-vij** [comment]
Poseidon has a scheduler loop that starts a Firmament scheduling round upon previous round’s completion. Poseidon/Firmament scheduler runs continuously and picks up however many pods are available in “Pending” state as part of the batch processing. This is all described in the Poseidon design document [https://github.com/kubernetes-sigs/poseidon/blob/master/docs/design/README.md](url).
