### ISSUE TITLE
Add comment to more functions and critical code blocks

### ISSUE THREAD

**Issue by lioncruise** [kubernetes-sigs/poseidon#20]
Recently I'm gonna do some secondary development on poseidon project, I find that few comments are in the project, which makes it harder to understand some complex functions or code blocks or causes some misunderstand. Good comments make reading source code more efficient, which could attract more community contributions. I'm appreciated if adding more and complete comments could be put on agenda.

**Comment by dhilipkumars** [comment]
Hi ! 
Totally agreed. We are working on it, our first focus is on integration test suite and improving UT coverage at the moment. Once that is done we will work on this. 

However please feel free to raise a PR with docs/comments for the easy once (those funcs you understood ) and add a TODO for those for which you need more clarity.

**Comment by m1093782566** [comment]
I would like to offer help to this task since it's also a good opportunity to familiar with the code base for the beginner.

**Comment by deepak-vij** [comment]
That would be really great Dujun. As Shiva is working on automating the e2e testing process for the new repo, it would be great to pick up the slack on the documentation/comments of the current codebase. Do reach out if you have any questions or need clarifications.

@shivramsrivastava @ICGog

**Comment by m1093782566** [comment]
Thanks @deepak-vij

**Comment by shivramsrivastava** [comment]
@m1093782566 Thanks for helping us.
I would suggest starting with the lint comment errors.
It would be great to see a PR for that.

**Comment by m1093782566** [comment]
@shivramsrivastava 

Thanks your suggestion, I will send a PR soon :)

**Comment by resouer** [comment]
I read this paper before, it’s a much interesting task than ipvs. Please
keep doing this and be free to let me know if u have any problem in
scheduler.

DuJun <notifications@github.com>于2018年4月8日 周日下午10:41写道：

**Comment by m1093782566** [comment]
I am going to close this issue since I have already put some comments in.

Any continuous work on that are always welcome.
