### ISSUE TITLE
Unfriendly import packages of github.com/kubernetes-sigs/poseidon/pkg

### ISSUE THREAD

**Issue by wgliang** [kubernetes-sigs/poseidon#24]
Just like:
https://github.com/kubernetes-sigs/poseidon/blob/master/docs/devel/README.md

Developers need to create new k8s.io directory under $GOPATH, but usually developers will directly fork poseidon to their $GOPATH/src/github.com/username/poseidon. If there is no k8s.io directory, go build will fail. If the developer modifies the code under github.com/kubernetes-sigs/poseidon/pkg, the changed code is not imported.

I suggest import kubernetes-sigs/poseidon/pkg/k8sclient directly or just using like staging of kubernetes.

**Comment by shivramsrivastava** [comment]
We follow the same workflow as mentioned [here](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md).

![Workflow](https://github.com/kubernetes/community/blob/master/contributors/guide/git_workflow.png)

One should follow the 'working_dir' pattern as mentioned above, others won't work.

1. Fork from the [here](https://github.com/kubernetes-sigs/poseidon)
2. Clone the fork in your work directory 

Note: The working_dir for Poseidon project should be 

```
working_dir=$GOPATH/src/k8s.io
```
```
$ mkdir -p $working_dir
$ cd $working_dir
$ git clone https://github.com/<username>/poseidon.git
```
If the k8s.io directory is not available in the path it will be created by the above ``` mkdir -p ``` command.

3.  Finally Add the remote upstream, to fetch and rebase from the main repo.

```
$ git remote add upstream https://github.com/kubernetes-sigs/poseidon.git
```
