### ISSUE TITLE
Create the official release for poseidon

### ISSUE THREAD

**Issue by m1093782566** [kubernetes-sigs/poseidon#38]
With the rapid development of the project, it is necessary for us to periodically public the poseidon release. So I propose:

* release cycle: monthly?

* release content: 
  - zip and tar packages of source code.
  - a docker image link, e.g. gcr.io/google_containers/poseidon-{ARCH}:{Version}. Supported ARCHs are amd64, arm, arm64, ppc64le, s390x and relase version is in the format of x.y.z.
  - a release tar package which consists of poseidon deployment manifests for kubernetes and a saved docker image file.
  - a brief description of notable changes.

@ms705  @ICGog @deepak-vij @shashidharatd @shivramsrivastava @dhilipkumars

**Comment by shivramsrivastava** [comment]
@m1093782566 Thanks for coming up with a release structure.

For few months at the beginning of the project we can have monthly release cycle, but later we can relax them and make it as and when there are some changes or bug fixes.
@shashidharatd 

Do we need to support so many architectures?
We can support Poseidon on various mentioned architecture, but I am not sure if we can support those in Firmament. 
@ICGog @ms705

**Comment by shashidharatd** [comment]
> For few months at the beginning of the project we can have monthly release cycle, but later we can relax them and make it as and when there are some changes or bug fixes.

Releasing frequently does not make sense unless there is lot of development. is there a roadmap for poseidon @shivramsrivastava ?

**Comment by shivramsrivastava** [comment]
@shashidharatd Yes we have one [here](https://github.com/kubernetes-sigs/poseidon#roadmap).

**Comment by m1093782566** [comment]
> For few months at the beginning of the project we can have monthly release cycle, but later we can relax them and make it as and when there are some changes or bug fixes.

Make sense to me.

**Comment by shashidharatd** [comment]
@m1093782566, i don't think there is a need to build release for so many architectures. My suggestion is to start with one i.e. `amd64`.
Also we could keep the saved tarball of container image apart from hosting the container image.
For hosting the container image under k8s.gcr.io, i am not aware of the policies.

**Comment by shashidharatd** [comment]
@m1093782566, saving the container image in release package would increase the size of package considerably. So this can be pursued if we are not able to come up with vanity name for our poseidon container image within `k8s.gcr.io`. 
Here is some discussion related to naming these images based on SIGs. I am not sure it is concluded.
https://groups.google.com/forum/#!msg/kubernetes-dev/zd3tySzuT9g/HT2ux-7UAAAJ

**Comment by m1093782566** [comment]
The Poseidon release is already available now.
