### ISSUE TITLE
Cannot build poseidon

### ISSUE THREAD

**Issue by marceloamaral** [kubernetes-sigs/poseidon#43]
I have tried to build poseidon by several different ways and no one has worked for me.

First, I tried the "go build ." and a got the following error:
can't load package: package k8s.io/poseidon: no Go files in /home/go/src/k8s.io/poseidon
I tired to google that, but could't fix it, do you know what is it missing?

Second, i just tried a simple "make", then, it does not find the kubernetes packages
can't load package: package k8s.io/kubernetes/hack/cmd/teststale: cannot find package "k8s.io/kubernetes/hack/cmd/teststale" in any of:
        /home/go-src/src/k8s.io/kubernetes/hack/cmd/teststale (from $GOROOT)
        /home/go/src/k8s.io/poseidon/_output/local/go/src/k8s.io/kubernetes/hack/cmd/teststale (from $GOPATH)
I found out that the /home/go/src/k8s.io/poseidon/_output/local/go/src/k8s.io/kubernetes/ points to /home/go/src/k8s.io/poseidon/ not to the real kubernetes folder in the GOPATH

Third, using the bazel : make bazel-build
then I get ERROR: infinite symlink expansion detected

Fourth, I have manually create the symbolic link with the  kubernetes folder in the GOPATH into the  /home/go/src/k8s.io/poseidon/_output/local/go/src/k8s.io/
It fix the infinite symlink, but fails with:
ERROR: error loading package '_output/local/go/src/k8s.io/kubernetes/pkg/generated/openapi': Extension file not found. Unable to load package for '//pkg/generated/openapi:def.bzl': BUILD file not found on package path
ERROR: error loading package '_output/local/go/src/k8s.io/kubernetes/pkg/generated/openapi': Extension file not found. Unable to load package for '//pkg/generated/openapi:def.bzl': BUILD file not found on package path
INFO: Elapsed time: 1.077s
FAILED: Build did NOT complete successfully (418 packages loaded)
    currently loading: _output/local/go/src/k8s.io/kubernetes/pkg/printers/intern\
alversion ... (7 packages)

Please, could you help to build Poseidon?

**Comment by marceloamaral** [comment]
Thanks @shivramsrivastava both ways worked for me!

Just a minor comment in the case someone else has a similar problem. To build with go, the documentation says to place poseidon in "$GOPATH/k8s.io/poseidon", but it should be in "$GOPATH/github.com/kubernetes-sigs/poseidon". It seems obvious but I took sometime to figure out. ;)

**Comment by shivramsrivastava** [comment]
@marceloamaral we have updated the [documentation](https://github.com/kubernetes-sigs/poseidon/blob/master/docs/devel/README.md).

**Comment by shivramsrivastava** [comment]
Closing this issue as it's resolved for you.
If you still have any issues with documentation, please raise an issue, we will fix them.

Thx
