### ISSUE TITLE
Support for Pod level Affinity and Anti-Affinity

### ISSUE THREAD

**Issue by deepak-vij** [kubernetes-sigs/poseidon#51]
Enable Pod level affinity & anti-affinity functionality within Firmament scheduler as per the Kubernetes Pod level affinity and anti-affinity Pod definitions.

**Comment by deepak-vij** [comment]
Here is the link to the Design Document for the ongoing Pod Affinity/Anti-Affinity implementation effort.

https://docs.google.com/document/d/1C68E1Thw7i9NGlHFwmnkgWmNSUK3z0oHdH2mLMK9Eyw/edit?usp=sharing

**Comment by shivramsrivastava** [comment]
Feature merged, hence closing this issue.
