### ISSUE TITLE
Support for Gang scheduling

### ISSUE THREAD

**Issue by deepak-vij** [kubernetes-sigs/poseidon#55]
Enable support for Gang scheduling within Firmament Scheduler. Some jobs cannot make progress unless all their tasks are running (for example, a synchronized iterative graph computation), while others can begin processing even as tasks are scheduled incrementally (e.g. a MapReduce job).

**Comment by resouer** [comment]
@deepak-vij  It would be good to see gang scheduling in this project :-) why not set it to higher priority? The default scheduler is also trying to ship this feature.

**Comment by m1093782566** [comment]
@resouer Because currently we are busy in developing pod affinity, taints & tolerations and preparing for performance test.

I think we can adjust the priority once we have all the tasks I mentioned done.

**Comment by deepak-vij** [comment]
Yes, we have been successfully able to enable the following Gang Scheduling functionality as part of Poseidon/Firmament scheduling:

1)	Strict Gang Scheduling: all-n (all or nothing) scheduling, some jobs cannot make progress unless all their tasks are schedulable.
2)	Relaxed Gang Scheduling: k-of-n scheduling, some jobs can begin processing even as tasks are scheduled incrementally.
 
We are still in the process of tying up loose ends for this, we will soon merge the latest code as part of the new Poseidon/Firmament release. Thanks.

**Comment by jiaxuanzhou** [comment]
@deepak-vij that's great!

**Comment by deepak-vij** [comment]
Here is the in-progress [design document](https://docs.google.com/document/d/1phQOkIgvjNFq8fuu-_yrzth2S7m0NPCoCGCf7K6U--w/edit?usp=sharing)

**Comment by deepak-vij** [comment]
We have already implemented basic Gang Scheduling functionality. Closing this issue.
