### ISSUE TITLE
Question about flag content in Docker run command

### ISSUE THREAD

**Issue by LernaeanHydra** [kubernetes-sigs/poseidon#6]
Hello @ICGog @ms705 ,
  I wanna integrate Firmament with Kubernetes running locally, however, I got confused when I  tried to run this command:
$ docker run camsas/poseidon:dev poseidon \
    --logtostderr \
    --kubeConfig=<path_kubeconfig_file> \
    --firmamentAddress=<host>:<port> \
    --statsServerAddress=<host>:<port> \
    --kubeVersion=<Major.Minor>

I don't know how to fill in path_kubeconfig_file and I don't know what the statsServerAddress means.
I will be grateful if somebody can help me!

**Comment by dhilipkumars** [comment]
Hi All,

Is this issue relevant now ?

**Comment by shivramsrivastava** [comment]
@LernaeanHydra We have updated the [documentation](https://github.com/kubernetes-sigs/poseidon/tree/master/docs/devel), it has all the info on how to run poseidon.

You can refer to this [section](https://github.com/kubernetes-sigs/poseidon/tree/master/docs/devel#running) on running poseidon docker container.

```path_kubeconfig_file``` is required to connect to the running local k8s cluster. 
   It's like a credential file which is needed to access the k8s cluster.

```statsServerAddress``` is the address of the stats server hosted in poseidon, this is used to get the cluster info from the heapster's custom poseidon sink. This cluster info will be used by Firmament knowledgebase while taking scheduling decision.

You can refer the [design document](https://github.com/kubernetes-sigs/poseidon#design) for more info.

I will be closing this issue for now, if you still have any issues, please raise an issue and let us know.
