### ISSUE TITLE
Run core e2e tests in the local cluster environment.

### ISSUE THREAD

**Issue by deepak-vij** [kubernetes-sigs/poseidon#63]

**Comment by m1093782566** [comment]
@deepak-vij Could you please describe this task a bit more?

**Comment by deepak-vij** [comment]
@m1093782566 Please see the following ongoing discussion in the following issue with Kevin. As I mentioned to Kevin that we are planning to do this exercise in the local cluster environment. Kevin suggested another way of running it as part of test.infra CI job. We will work on all this task once we have completed our ongoing node-affinity work, we have few urgent issues to resolve for this ongoijg work. 

https://github.com/kubernetes-sigs/poseidon/issues/60

**Comment by deepak-vij** [comment]
Closing this issue as e2e testing is completed now.
