### ISSUE TITLE
[k8s Incubation] Requesting project transfer

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes-sigs/poseidon#7]
Hi @ms705 and @ICGog,

As discussed and agreed over the email, could you please initiate the transfer to [this](https://github.com/kubernetes-sigs) new github organization and to [Tim](https://github.com/timothysc) please?  This will be first step of incubating Poseidon into kubernetes eco-system. 

Approvers (People with Commit access): @ms705 @ICGog @shivramsrivastava 
Revieweres (People who can lgtm PRs) : @dhilipkumars  [two more to be added post incubation]

cc: @timothysc @shivramsrivastava @deepak-vij

Hi @timothysc,

Shouldnt all of us be added into the kubernetes-sigs org for us to effectively manage the project? Could we do anything to make that happen like send an email to some one with list of members to be added.

Also do you think it would make sense to create two github groups in kubernetes-sigs organization such that
1) poseidon-approvers
2) poseidon-reviewers

Regards,
Dhilip

PS: We could keep this issue for discussing other logistic related problems to bring this task to a closer.  WDYT?

**Comment by timothysc** [comment]
The transfer needs to be sent to the https://github.com/kubernetes-sigs  org.  

I've started a team https://github.com/orgs/kubernetes-sigs/teams/kubernetes-sig-scheduling but can't do much until the transfer is done.

**Comment by ms705** [comment]
Happy to do the transfer, but if I try to transfer the repo directly to `kubernetes-sigs`, I get told

> You don’t have the permission to create repositories on kubernetes-sigs

Should we transfer it to @timothysc initially, or is there another way?

**Comment by timothysc** [comment]
try transferring to me 1st then I can transfer to the org, please make sure you keep a backup too.

**Comment by ms705** [comment]
> You can only transfer a repository from an organization to yourself at this time

I'll try transferring it to me, then to you.

**Comment by timothysc** [comment]
Looks like it's transferred!  I'll update names and owners in a bit.

**Comment by dhilipkumars** [comment]
Cool Congratulations all this is an official kubernetes incubation project now. :-)

Hi @timothysc, How do we become part of this organization? would you be able to invite us?
