### ISSUE TITLE
Support for node selector

### ISSUE THREAD

**Issue by m1093782566** [kubernetes-sigs/poseidon#77]
There is a PR adding e2e test cases related to node selector, but it keeps failing now. Probably because node selector which poseidon scheduler doesn't work properly. We need to figure it out.

@deepak-vij  @kevin-wangzefeng 

/assign @m1093782566 @shivramsrivastava

**Comment by shivramsrivastava** [comment]
The PR #73 for node selector e2e test is passing now.
All issues fixed and the PR is merged now.
Hence closing this issue.
