### ISSUE TITLE
Add support for max pod number hard requirement

### ISSUE THREAD

**Issue by m1093782566** [kubernetes-sigs/poseidon#88]
**User story:** 

If node A can only run 10 Pods and already has 10 Pods running on it. Then, any Pod can't be scheduled to node A until the number of Pods running on node A decreases to less than 10.

**NOTE:** can we resolve it via CPU most model?

**Comment by shivramsrivastava** [comment]
@m1093782566 Where do you want to specify this limit on a node?
Via a node lable?

**Comment by shivramsrivastava** [comment]
You can limit the number of pods running in a node by setting the below flag on the firmament side.

```--max_multi_arcs_for_cpu=10```

But this will have a global effect, means firmament will not allow more than ```'10'``` task on any node in the cluster.

Currently, we don't have any capability to enable this on per node basis.
If you can further clarify your requirements it will be helpful.

**Comment by m1093782566** [comment]
@shivramsrivastava 

There is a predicate in the default scheduler - PodFitsResource, xref: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L695-L698

**Comment by m1093782566** [comment]
Meanwhile, there is an e2e test case in the default scheduler, xref: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/predicates.go#L120

**Comment by m1093782566** [comment]
@bentheelder

@islinwb is a kubernetes org member, why we can't assign issue to him? It's a bug?

**Comment by BenTheElder** [comment]
@m1093782566 for kubernetes-sigs it has to be that org instead (or a repo collaborator).

**Comment by m1093782566** [comment]
Oh, I got it. Thanks @BenTheElder !

**Comment by BenTheElder** [comment]
NP, as far as I know this is a GitHub limitation. I think soon we will get around this by having a tool automatically invite users from the kubernetes org to this one.

**Comment by m1093782566** [comment]
That would be great! @BenTheElder

**Comment by deepak-vij** [comment]
Here is the link to the Design Document for the ongoing “Max Pods Allowed per Node” effort.

https://docs.google.com/document/d/193mSheIQomIWQQVG0jFQe76Vp9QVbu5K8EOI_20Jilc/edit#
